creation_rules:
- encrypted_regex: '^(data|stringData)$'
  # Base is shared, you can add keys from each environment that uses base here
  pgp: 6104D2F392444CC8243547B470FFB5728BB9FFFC
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: 6104D2F392444CC8243547B470FFB5728BB9FFFC
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
