apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apps
  namespace: bigbang
spec:
  chart:
    spec:
      chart: ./apps/chart
      sourceRef:
        kind: GitRepository
        name: environment-repo
  install: {}
  interval: 1m
  targetNamespace: apps
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: bigbang
      namespace: bigbang
  valuesFrom:
    - kind: ConfigMap
      name: common
    - kind: ConfigMap
      name: environment
    - kind: Secret
      name: private-git
      valuesKey: username
      targetPath: gitCredentials.username
    - kind: Secret
      name: private-git
      valuesKey: password
      targetPath: gitCredentials.password
  values:
    gitBranch: env/bc
    # hostname: isa.bigbang.dev

