apiVersion: v1
kind: Secret
type: Opaque
metadata:
   name: private-git
   namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.gitCredentials.username }}
  password: {{ .Values.gitCredentials.password }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: apps-repo
  namespace: {{ .Release.Namespace }}
spec:
  interval: 1m
  gitImplementation: libgit2
  url: https://azure-ecosystem.visualstudio.com/Azure%20Gov%20Engineering/_git/dsop-environment
  ref:
    branch: {{ .Values.gitBranch }}
  secretRef:
    name: private-git
