# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base?ref=1.11.0
resources:
  - istio-gw-cert.enc.yaml
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
  - secrets.enc.yaml
  - |-
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: bigbang
    spec:
      ref:
        $patch: replace
        tag: "1.11.0"
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: source-controller
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
        app: source-controller
      spec:
       containers:
       - args:
         - --events-addr=http://notification-controller/
         - --watch-all-namespaces=true
         - --log-level=info
         - --log-encoding=json
         - --enable-leader-election
         - --storage-path=/data
         - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
         env:
         - name: HTTP_PROXY
           value: http://proxy-zsgov.external.lmco.com:80
         - name: HTTPS_PROXY
           value: http://proxy-zsgov.external.lmco.com:80n 
         - name: http_proxy
           value: http://proxy-zsgov.external.lmco.com:80
         - name: https_proxy
           value: http://proxy-zsgov.external.lmco.com:80
         - name: NO_PROXY
           value: 10.0.0.0/0,166.22.158.0/16,*.lmco.com,*.amazonaws.com,169.254.169.254,192.91.147.*,localhost