apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:vXxQG5ibwGMYqYwhaGQ7GYmLauaASRhvtsPXguK42zYPDrw0MizBZ800fbvVxpilCkePB/iLvCiS77wFPPRZv50PkYIWDUQS7IQEd0WGHa5MOGkpL6zStrAoi8RXETScGaWT5GH/H6maFy+bZ1JiMz5vOxRvb5lh8LhAHIgh,iv:4cTXmxouXBWsZytdeZeEyOuyZcQGhVgqOcf9z9Qglm8=,tag:e07dUTdH4n2vRa/+6Fr6Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-11T17:33:26Z"
    mac: ENC[AES256_GCM,data:dGdQa2oZb+LUixQdr8zjmTzHvc54tq9tqTv05CuFqE8idzcRqwoGgwgBrVCZ3EDS3G7jXRImX9BjXL222WWr4oAZ94W54zEVNT+DkanaMemk7igVlSTgQBrMM2fdRMkpd28nJz+LInb3VTyV/n9g6cfjXXwGnV7RX46UiyDmw8I=,iv:DlAnwoQ6FtO222iZqH/vp8sgfWZgikVWQ+GkNg7vBBY=,tag:8AkAffbJIOcky4hMgoJ0IQ==,type:str]
    pgp:
        - created_at: "2022-02-11T17:33:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/MfR77dm/cVAQ//XT56pHpE46FFsaQFm6Bdipky1sCX2YmQjzMeEfPJFyDD
            qTy2zz9I5xHdPIVWyLJxjVn5ZpGY4gL6xtV9RARHdEo4cTk1/toGG6cNiCAPHX6V
            T/jXXNdsuO7ear/QxsTs4x5uBLKMs3hCxSj3D5zV9kRBj1zKtsUDz8lSZbj95Q2M
            QCnNCdCR4BnM1NgIzQAnehBeWOnAmvoOjSlD8BzXnxNnZU3oKy6cXCleo1auGyQ4
            WKvb1vV9YhGI1gdJeVlnruUJAmnb3aCP56EqHV75rt0YOeX4lXnfy4t+sNeK4U+t
            BTwQqKmCwKEoH4deG90CDLfYaXev1TIuzRUXn2zlsxSEowY5BlLdvHGzl3BZvN8B
            hcKZvE2o9/eH0nzyuCUAPqdzLBUW/UJhac/sd8I0cJoWLg2KRe5HEB6yFF4+59t+
            OYdBKEI0YT0M18wSoQb+5R8Yf5LWSxc64c7n2dkMa7saqIqGUsocwMoMoTe+6LAp
            nv87mcedmNwq5NyWt+fMb1F91tU1KBnr/h2JGCcFHC3oLRpGdJCd/jSwdeeBp2Ku
            7hCxRNTsKlzr9C7+AwbWIgGc/StDmwNZmz4zqzNUd+yTSpS0rCLaVxaMQBtmvujz
            3hQYlJzF0NwiKplCr7WC2vbKBoh42Dk7UcvLFQbNw1iurc1BFmhaIAqXwtJ9ZX7S
            XgG77fqKIStm728gVonc/WD23FL1p8W8ml6cOUaVDn6HbxtjT58eghyCeu3xqQyM
            MJgT2zr1x47wfIizVEo8DqPFrlBCSncczdQDpL37V9eM0x5KFPKhdB5koNCG3B8=
            =mcoR
            -----END PGP MESSAGE-----
          fp: 8ED860B8582DFA86CF887B228E9A833FECDB2CEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
