apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:CxLXODMaToJjQxukfhWJ46Sjbp4ZA8+iYAidj4ImuC0lUqEcYKj7bPt7LgYrN3cmeqmrYHeIf//nD1RDLmv59ysJV20w1TOV31odKhc9r7Hed/izXohBFrEnb8Hr/N3L+0tZcU6UTox7HJdXAZOarVorCesHLLXhWWgtRWjp,iv:Qmh6+nWp30GlfbpXkUCi4i/1F1PqqE9Xp0OjP3Xxji4=,tag:zOcgrwJoKvMj1b+oLjjLOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-28T18:36:13Z"
    mac: ENC[AES256_GCM,data:/7jwEetIhrF6fd+AhMGTrumFis78skg8mohjuvEghBc14V1TFyRcKLaT+9HgINpE+aTlO1+yPlCAIWg5CcmwCWlmCV4Uw7rPgSI0Gxel2NL6m8eOTXodmqJvgyS5iJMj5KgGlb8EVJV61Iys8d1GzVQFHCi3luG/fNfqsV9fHQo=,iv:IAe7Cpeld5oWZRVV4sjNJOtOV392/hnc3VpOnl9gINY=,tag:PNmnL2/QZ/OinNcUJrLYkg==,type:str]
    pgp:
        - created_at: "2022-01-28T18:36:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/MfR77dm/cVARAAgMbVm/7gOKu4QKrhsr4GSK9Nt0RG5jZNXk+/ZAXGiCEp
            AsxtJ3PK/D94Z48nrbK+pfhdClN47fU/EWD/WV9ELbPQjhEmeGyvtUTpqua1DdyM
            LyNavikL8Lbw7nR8XW9Nr2H+YKOIhzVYoH38OOB0t5DRpnuN2OYer/o8KgYpmwhW
            khDWBwdr8zXgFeI5J1aDY6ZAfBA7Z55yk2lv+Jiwi6pyx5bDsnuf8eclhrCMt62l
            5Cea7HjIClLmvKdt+hpq6tBA1PMcGTmY4cxIJRJeRvKHBRPWkMTJWsKL/Zy73gJX
            qs00BfsPSbfR5kKTjvLNeYgw9ADl4MsJNz8IF4MbVRClaAncQ7glO15zBJcgc9kc
            riSUyDJ2YCP9gHAJnmt0ommqLR5Lkuy0WYthSyATQSiNqKUhyKrztnLOb97whw7p
            ePbv6m7lS9pdu3hOBB58eEZbfut97Vp005URqEHCKcwDe53LNZdhaH2M+mEg/5dj
            LhO75vB/Vl4ueqSEpu/W+GgUGfGya7cqVj2AhW2/0Dikw1SkNPu8VS/IJc7rcBiP
            niAXcim8LJ6trfg7jZpb4Qq0uUF9ffQ7RQa4RC3bPXtedS6eviImB/cr/mNcefO5
            uH+kXld3l8PJvOmW12SuSmmvP1uKKmVzou9j+4yRPJr2GlQfZLC7vjX3XF4BhWbS
            XgEgnP/IRam/mcr51RfTH8F1v5JATvfNy8qUR7uUo04LeEjmc6aqe/np/lAInI8g
            ZBQdVGF8OPbZG5xHQqCsYSlT+/Nfd3ANs+pnlc4e9zimYLnFv9G+dSpgwjsZyc0=
            =XFDI
            -----END PGP MESSAGE-----
          fp: 8ED860B8582DFA86CF887B228E9A833FECDB2CEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
