apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:krSvJbQ3BoOJyhxr8gq3JCDxf2vLu67UWQHvp0s/m3d/Ue5PRtspm0X82NsWXAheLiGEG0mKetVJwPQ5bs/WGDiBfO4a//CV+bGSfRW9MxUpYsZ7dxOc86k00XQw9wwlY+9TxAbniK0vnEHdCWuMbPjsH2vO0Cljbad+L/Ay,iv:19KL9xESdaPbz4DVWQyYSumtPgLTwpMw5h8zK2JuX+A=,tag:aj/C/62liN+mSYuCxeoR7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-10T04:48:21Z"
    mac: ENC[AES256_GCM,data:OBeaRzKd0Iq0eJ4nAOSnDZlhUzw1jM8MCtauZ0P/Gds4cNYeWXkyT/oplFuuB6aZijAwWk6zIJhwtAViIGbRy9ShcHEcxA4efIDhJXz8hJGAoaq3xMrOeazDwKzYdgBTe7taZszF/9wETyyoUxql1gHoEVPK2s0rfH4gEGgAIJs=,iv:/mnJG1So0Hy8xhTlmer6ZCDEmVqN0Cc9aJV35GdteU4=,tag:bucquRo08KT+q5EXC7v4Tg==,type:str]
    pgp:
        - created_at: "2022-03-10T04:48:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/MfR77dm/cVAQ//ZbN+z+319Mp3obtta81Qh48WdRylSxd3CBD917odNjQv
            yFgpgFPa9BY/qtJmq7/jWajZqpkmHHhK+s6FZTESJZhaVCwcZ3sISeaMhKJxo/0Y
            Xp7BYT6hbffzbjC6D6oHjQ/7z0uUQ7e4Yg+yWGoXPjw5A8Dzvq8f48f6EqtPwQA6
            rXg/6Pcd2O74EfqXjMSkGTmrFrutRjUth/0jL8sJUf1IB9DYvQkys8ZhwwOueVo3
            w3O0VmZpK2YjOQl49//vKSBwBsHCXR680ac0bEeu4XymOZxdiT0G65KbJsnlMsID
            cNQJZPjDZiCHH2X+TvRc8z4Vqr2OntkTVkFZi4+MJxdIBzaHRosvNht2KeaA70TK
            Yu/MJoRjmLb3qSfpzgdLZcXMk/Lg68GbHkZnYM6cjkiwl9z7lKr7Yl1f3La8vjZs
            ydwv4syQxOxzQTHbD3Q72bRkXbpevwr3EoYWa1KsTUMIPGR7pe4tQB0J3yb3Dj9K
            EUTHH9klPFDoXo8klNavgSYgwHXZN90wWcp7odvLEyiEgtPH8BrtC4xWG7rxdQwY
            9UzobTCEZ4iOCUXhRyKxCVc6ud4a/CadZMeaS3ZEIVwCsH12qL6J55rWauQHBBpb
            8NvNZJtGmvHXHJIkI/RW2JkfgqPgcLEm3NgXxqEWnhTyMW3ALNW3RsZP2mtrXArS
            XAGex+cou4OjeHkVzRzJPAl0K8mVlOBwLYYQiOJ4JLHHYvF8aSVYB8JL5UsjKMvd
            ftJcEZ7yvX9x5c1/MAss3M1VsezBn7E298cd/NLcD/+yGUj9Cfwc8xvwdOG+
            =w6/9
            -----END PGP MESSAGE-----
          fp: 8ED860B8582DFA86CF887B228E9A833FECDB2CEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
