apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:9Fv49fD3zE5TYIcOUfou2th0hcBILTGEJub6xP9PSIrjLKZmcnjpcHe9CTK7vfTgFGAVRQda4g4SCmyXhJXZ1N5ZsB/slRIWQNOrYsMF7boaeKGK5k3iuilYSG9KckpupPRi6D3C7hxur10RvcnTFPTY2xuTovGP4S+c1qx2,iv:EG3Whm7zRx9O/8tbFj3oYtyK6b0W5PLa2oATVANSqDg=,tag:ybyEBjhjkKR1y0B7eGK4kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T02:19:27Z"
    mac: ENC[AES256_GCM,data:jNwKrgya/e07StMBfzve9sgsuFFxy/bTcnlg+OiACDlYnLJ60zJPhsuJuEsx51RR8CQCSURsLSsrCvoje/kflIK15PT7baIbHJavJqRKgtyViXQq5GRUNg3ewJpddmZ2Mce8aOh46rYKcRICl5Eiv2xNNSfjOSyjzfCrOAYfQao=,iv:OXxXwshEV7qFx3ha3tM64CdzeYuNwxg7scXISE7/0sM=,tag:KdQdDtM582T8bg14Rq4JFQ==,type:str]
    pgp:
        - created_at: "2021-10-26T02:19:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75mp9mXYKrEAQ/9FEyyqB7ae5CXeZ0jtkhSzUM8+ZX3efNyuOuXu67SBruS
            9Z3WL6i1DuTQ7eaNs2YlVPUGi8806H57Ni0iLRgtvSnmxvy/2BUKpIgGsjn0XgJm
            CaPTV+40DiWmvHz3sNbSe4aQLQ1D0lhTO4L55p6XWvNh3+lsA5AgP4tc0IPenDek
            WCDE1WdRBpA/IFrnyLn37GoeXm62ij01nwbAg4mGiLCnuN+J/4I66QOCF+yz4qXR
            DSm6ZbHCp8PObkJmKdBnyyECOhclbAKMtAKrfLQF6iJTZn2BSYMGvxq3hlSN1ruV
            VbS9r9KdffYupi7yE8nHSchJ6hynB57tVA9cPtXFq/5kBszxrW9xI+itWQeBryfb
            BivDtWjeoS9CxNv5CXLJPMYCqBlaEz4+JUicNWVrd4pFexw+6thG23lQmSYdMdcb
            mzRg0fWK3JozhzsNZhwSUGLapYljPqEjxiQbrbiEAiGqyKtbsDfmu8bFXmkPAObe
            /AVln+CAmEblPjTLhz1WkzsUS8l+PMr1xKgIrNisoGOyIk+pYohWJZYAB5AtTDhj
            DhYXu5NfLXI2b7NrXAJo1srgL3qhtPBrN0jd2vzwvkTbvM9xbdDc+xzrBLTHo9Vf
            +AfQXT4RTWwEL8OPL0zN/ytLJVOAxutKarpvyv/rJJnJuH+GgLaYBJQALMHAcRnS
            XAE0MnLk49qV1/P0v5QAIJywinUw1PzTyOrQV9YyIAAIncM7BgmKbTsO4J/0cyP8
            EJsFAOWlUbEVxzkmXH55suvXd/NaIBTkGuy9XPpZNv0eIcfc2XodQNy2A8Sg
            =zweK
            -----END PGP MESSAGE-----
          fp: E73C7B034BE4607FFACA2F6EEDC4FA3BE4FBBDFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
