apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:pL3coZcsYIAixQAeLPrxw2vhJ4gBOrg2kmYpB/H4Nz93UfDjwc+w/zk3/W7ohk/GimFy/vmJESsHsNrg10qi/qFJ7oikF4S52xPo8sSuVvULLFsBm74BofGplSjCPFwY0C0ZRuTLafJpPPmT7+kmq1Na+cSa/R+DQaV4s+Pq,iv:YNhTBsRFB156901ZIe+50IHHGssmGeRekV8yLYViF8c=,tag:P/1XpDO1X4Sm0h+kpQ8YgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T03:47:15Z"
    mac: ENC[AES256_GCM,data:WcCZz+ojfmoM/1vqBqzCnYKtHlpYd5nP0n9qIhD4Bp3a4JsMm6whisnAQEEso0WtiU1cdoSyS5tJjfwuBubWyI1oIlmeGMfsZA0T053x6SD/CAhk1e+m1P9TZ8gNjyHkdPFbUE1efNK3fJ5PTKGlpmbn5fsi+snaZ9Dn2kztPic=,iv:Aw0GM6cUzBuwvIbAgHV0cpdi81vPQ0XGlXRA0e0vYso=,tag:sMB5LAbqteXdn07EwayPRw==,type:str]
    pgp:
        - created_at: "2021-10-26T03:47:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75mp9mXYKrEAQ//SIydq0U3i6qt3+pRnBe7igCAEnyTn7yaCxgrpSX/Tj/5
            lryxH+P2BKh7Qi84JYc5k6l/MY+5A0StmXqiLwfZRx9EB1JtjLSL8xTjkLRH+BZM
            JejJKptJDN+EUnLIalkL70WBOmiB+fh/Kl/j1Mf5kEMb5t+D4BBSYzRAX1zO4BTz
            /41fi7+b8KO4FRi9z7DOPKUsykaw7ihZX8ny/l+BEsMa7ItkZMoKcUdpylULII2O
            tGoZWTIDZRonU4JCeRrid95jpJ8uj4P2ZKrCvw8x6UYigwGThED8Rvcq32ySHRIG
            1jnBajLbyBJNVCH6zDuSfgeS3fYMQXWg0iKLgZNcmsA/uH8jXq93p6hhhh4Od0pX
            zj1CWJVOJahhe6cwLmrozDGHi8HEF35tjEGwO3eO1mUfvhkb4Ioa6qNIW+MBOcEc
            DrzTU9UnaHWgQMSsF4SrOVEg2mn0bP0mozWKTyqlP2kEXBVitFzbbdolS48F6qbP
            eUmk6MCgrACWCMfPpTw3PSZHkrX8X0d0lsm0HzdQjyq8LASBHGwAhrjTE3/qslct
            tj3WzpRgmjf8dI8g5znPWxyQPLRSd7tQ1ZkxyCMxApOQc1w/sYDiYVcDcBSrHhrx
            TRb05iKcDs6VBEvR3mUU6vAE0m9nCeRMXbmTzDBplgutl5vEJ1RmGPwYOkUgAtnS
            XAEMLi5s9LLAcKBXiSPpyLug4AR/VZ6+NeuY17NaB/Gb0GRMvCHDo0cOHjq0r58X
            z96Rvdc7x4zvj4IJpnvvzmWAYLHq6u7GN8bGWGGVpNDBRQ2VdoZBnGFPIxrT
            =YlxE
            -----END PGP MESSAGE-----
          fp: E73C7B034BE4607FFACA2F6EEDC4FA3BE4FBBDFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
