apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:Rql2rupNImoFXxO3+7H09hlbbb51ne1IRkk7TDN4B3Y/upoRBftoE8GgMzeE6wCEvfEpd1wegdnAct+nSR0Q7S2W6QOn02rqi9QRnV0V5GuoRoWKQR66mNqvetVxu06Cv21m/ZmmElssHMeF6/vdykGdHrYjipzM6rynw0fN,iv:4WqlASc5uTNmdYLa6S8fPsfD727fGjOdcoqq0Os100M=,tag:XQP5ijcAe0fu4WVqomualg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-09T20:47:52Z"
    mac: ENC[AES256_GCM,data:mbSYv7415y0/61PiNPbQ2VDfAtl981hSncsuyz7L7FZ1G1pOhJTlBkxroEDEMyKsMnnh7ZyZO14cGO1Kn02O6i8quHrcR3YXl8tfTJHbGMpD+J7XRM5AG3d+FjCMCFawAVYNS/ubeDp+F4/qf7SS4laZyUjkdj7p0nB852xUKHo=,iv:rw4sHcnZaSegnpPUAk1beAbttAxBQ8zN7u9K7NsTDD0=,tag:7Pttkd7v+LUgTEW6w1tI7A==,type:str]
    pgp:
        - created_at: "2022-03-09T20:47:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/MfR77dm/cVARAAjEKJ94FpquGKkgnTLZiGA3vIVqpkNygN9FRfG69941cN
            vmnQqEcIuDfxXyEHfAUFrpVFaFb980Pgdo10N1nYmzxdcdJU0nudCZB69nrWMnuL
            JYrcaK7YlIZ3+pgL7TnvD5pFmDn0XHsh5Px6MRo5FKXQyksfJbbxP/nIMKF/xkgh
            +Jtrsjjw/RGsaK+sKytTuLRnU8RY+RWjIU2gE+3q1r61i+cDLktwiyU0NU7jyfXp
            VyQFAhZUMhCW0BPcxyqA+SgYY6wYSRE4uwNEjrDAB1LGeYAyfm3FN+7hG8CUeE24
            BtfuYWc0du3oKyR4xkA5rQweJRe8GvNtzhEiUa9qk7QPA9cDT2MQP+Q0+DmzxGWO
            oUy/hi8aIqwRpsyOvpfgxEuuKENodEFeuj1m60yqOiekcH7JEKGHzbRBK7gjXLQa
            r6RSP+57vmJYKGbXiKxPVuRph2zUVXaWEMVI97rT4aQ6ogbRrpLE79jFOk7YAGXn
            lT4eiwT62GSMmUVvCRGIGi6RpOjU8sX4003aBVpa/MSy9eld9n/KWDXqi6teXxHz
            nNxwN/+VMlQSdBk0wwRzlrw3CGU4s6H33Qbwe6FcRNORZj0MaM0h0ykzn8ggwMKD
            04aPbnR+UDeqrMrHvu/Mcj3NjNDV1m6RqWj2wrQOtwvgMjYdn0+RMVIQA0WRylDS
            XgHMayGIGZhDd7r7JZbCO4ouvCxXdJoXlqUrgSdQFDQG6OWyY4HaZ5F5Fy9wn8CV
            xUXW8KCF8bhZHSnkYDvP6GBGdJmB1v5FKZW66HrLP+fccQQpPjc4VWv6y2DNXYw=
            =CA4I
            -----END PGP MESSAGE-----
          fp: 8ED860B8582DFA86CF887B228E9A833FECDB2CEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
