apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:LJybPMXd4HVMIRlTnhjeC90dqL/IQCoQZyCba1biUKeD7+2KMikL8ONNot9o/8ds6aZcTMUfhsLrukMSlZIU1Fo8NfX6lNCDgHZQvo/hPCIZoiVwRq4Q/MRHHy96j3RCmOC9lKAl/k4hV3tsek/F5pYWSeMVtTzzXvk5DbO+,iv:s4D+BgpfhfZnvr0iTdEHbHtnDh3wCi8BYWzuS9C5Yk0=,tag:y4d83eJlNLjDl6W/K2NBGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-08T00:29:59Z"
    mac: ENC[AES256_GCM,data:T4Kj0b3Hd3BjsaDJ7b4ci38+6kOpbJyhWICk+nWTi9yo6oQVjgjVHMeW2umRg+0QJyMKQnaBv/kE/DaBkcp5kf4ZwfJPSbs0SH2Ln9d9sTTr76YzcFVg8uGRoW4+YcUhT4wfshOJApg5WxNYtaDxOhGRkrw7xo2v1dY9+rjaDZo=,iv:m0CQX+/KSf+U1ZsLLTLk+1J6ed28bEx9lf8+CvbbBvc=,tag:oRUXctUweDQwxRRO9deEmg==,type:str]
    pgp:
        - created_at: "2022-03-08T00:29:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAy6Q8ZV0RebhAQ//fvUG8H6kAIa7/VxINTowUMBvslZ9FqWS9GtMBBhU7QKr
            02VC/VNcM/LDXJ+SQdsCs4kCopkCKQGcVQGqoGpZLMrA5nWDf2wGD8p3cq7bq9zA
            DKLNRbG2FMQi+aAaGiD/Yffk1io3Bs+EecHzXxGeO/8/VuJQIXPy/iEqCp+Uh6pB
            k8LETc8igphs+KYNw/wUUrdgngnWdylwhPHH+3wR2uIkhm9SaBppUOHMyUmtMWuL
            Qi4CuF5B848StMo/6C8S7Px9b/pI869PmOPmZBxdJdFoRUI7gHgGvtdv6xWrAV3z
            FJqe7FkIP8FMCpksWp1bSkhYFgLo2JvJi3mDoBqpqFCp1aoeTWXRX6A0Ir8AUej+
            BrvTCxAX1VUr8sIXYGo80cyRH1I4q5E2xG34sT/GkvQ3k8uYPGz4zKzlXeYzoq6G
            EIX2RNjQk0gOTMhhuNfVA6Dy3GTKfRRPshVPLhxNbGOvP/Kp990XqGCnkD0DEvMM
            LJbl0W8s3ZrmSLcwmgYBNqlrTMVstRUeoQ2ml5yIet8N0LgI3uSgUutc6sZm225/
            0nHjFTZZqpIAHwgoTGwXNTGysT851ONUBlZulAWA5nYQEsMNev/hRWcsu4MmubBB
            KWP6JWpsD8fRjlK9L+82AitMbNa0KDrPEMpbje/tlOrdl0qpxj293ha42gOF+uvS
            XgE0OAGP2E2Rm+S7Fg9DcEIAb/YOHgmJAmmoS8pUsckVX4SxkxSG7aNgh3Gh6QqY
            NivqExXlB/XBwMKt+q15eMEb1vx74cMmud5Gq9LOzk/JOOTwgEorfLFbYcb6swQ=
            =LyHt
            -----END PGP MESSAGE-----
          fp: 9FC5692D3CD69B08CFAA05E07D4EB024C03BC25C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
