apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:zDgo8uWmI5MkGAreQTkLAuOUcyvo86dVrzYIgJMheOvsLNv5xxopAfje12gbogf5njyOLwcsk1IhWBakkbWgdDV2OvII7w0RQaH247AnWoIqWPkXFGAV8EkalReMNjrlV4BVUtdgFu3mpfrWaNYqeiQndFlKOSzYmYt+f32d,iv:0zkFsW3u0PJNU4EHW8oWBSe9OuBMnAcFDpt+bIGzGvc=,tag:8+kAy8W+qjL8mpuWlg8OFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T02:19:06Z"
    mac: ENC[AES256_GCM,data:uCioGu8dzp1jyuEDyv9gzJiFe8iTM6OHgn3rAvh3zrXF7VubEjprpvq0R6Qg3e0k/GycERxOP8k+ULcEWPFmesBfaxGBVXNkPWJMIi/gHkotF7V3yngmYU+1JhoIZYobguv205HAbcbg1KScOTYtlLrOlyYq/wqfKsnIrDvP0QY=,iv:64YgB2Vrwc/e6+YObFVY8fxl5Oa14uW6qNnAtX9VDlE=,tag:NZM0OsHmPPvtYl4M8n7amQ==,type:str]
    pgp:
        - created_at: "2021-10-26T02:19:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75mp9mXYKrEAQ/+IPymphKTdW1suy9Gcf/BkM2KYLQLDXKrtJg/97VmVNeZ
            HklnvJiz0sg1K+WKlfhxvobi97Qc+GDOCrRo+ypV/7s/uDawIUjpex1wHozjszbf
            p07m70pK9yg9iKOli/FUoin1f3wBwILGVtg74CXLYLkKjN2BFVOKkh9cS+xTSVoP
            V7epZ4i6IYkbKDr94JXj8dbrnvVxFCMEljKFAFNlMcYpaJhVEZ6USz3iET136l3/
            THuZN4odV6colkQMyxhdQEv9CLfGWSVR9lr49OLSsdlItIdsKy2pS82nt9Sr1VRV
            he7KKxnKlP42iGyq4uZkGWXqw9EcBVfTD0sPnAbwtbmk2EBLaeyKJcq/caHD03nK
            C+3L/BgzfNy6u1QAFc1A6O3oWPBiRNOo+dKpn1KAOFOFXnNAzQtOdtZCLoVv7aGD
            +XMVHplcsbbnYCcaVcXk1pQYrTkio1ybvNeV94cPmsuQwWWgvIbucQubfNt5HS0f
            mBjT/NTnkDeohCy9h31sVryW8nzqNEppsXv2jT6k8KVlZkjxQ+BpCLR5f1kGxt2U
            aRrhaOihlEMqhV0PELkFPxNfB73ebsSmBkxZ8bpEYykqUMafH4sE1848OrDzQ2x1
            96LIrZU1t2W/Q9YVmhHyZCTj+Z/Kjjk60LHm285V1RH3rKgPidpHJGPBw+MYNH3S
            XgETUljVi4Um/v7+7C9iievCaJm2oXkNcIBjEAD2dicg94/v+cmx0AhFWOG1BlAT
            P2uDwsYSEtV8X0s62i7WNEsgr+p8Us406X/P4Erhj9PayCo/FlPEX88poG7gJfs=
            =Yi2N
            -----END PGP MESSAGE-----
          fp: E73C7B034BE4607FFACA2F6EEDC4FA3BE4FBBDFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
