apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:+rbxV7WcqWOjskL0OIx1WwQ1bbKNLp37Y+f+pBwbz1ONJDtNz4/3cZnW8U0MwbeLLr79kE1O2fGxJDFaO/kN6+ljlToGi2kqyJD03Rr5940kEFuQ7o/V5iP8nWTpOqU3/oSaEyvP4VAPMT1htv640/1l7bIoOe/OuIRQKtat,iv:cl9pGg6EpTort4AQ7iC3h+gwf+tf1DOcSn7Zd0kxbxw=,tag:ugeizNagxa51sHTVkmIxmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-10T19:59:46Z"
    mac: ENC[AES256_GCM,data:WYMQZPYr0vcUnowUq3jAoin6Qgjr8zmfH0N4zMuNk96YCKGzfpymJtVRztC+ed9Km9hY69CHbpA+BQQFqqP8OaKK24LVfa2J1s+no1uoxtYimvRpHyzuVwTio8SiZYJsf329AUzYZGbDQh18XdQxca4ijpcHRQSsR4UZrY6sWv8=,iv:lPaNnY5SX72NcJAYwF7SmOowbZEQqS0wtzADX4Y+S+4=,tag:kVHFuPQs98HRaLf6EHL01w==,type:str]
    pgp:
        - created_at: "2022-03-10T19:59:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/MfR77dm/cVAQ//eAH2Gsz428mDdRTt87MSkDEiP1vqBOBbljadDDMeA46E
            vNY8lUkvKN0Xt/ai1JLW9HNh7ftXBwnscurSCjwej6sCQ8frORI1TBxfqND9gxuO
            gxwz4kBjfsCsODeO+tIwPhCD0YeUDdxqLQsErzshpMjtdBRwqR4Rz8wa+QVvcIBE
            gfwspp7110xrpjI7oQpi44XDVYoqeNx6bpR9CWROTrZd+Q8DPVJv3hVSGU+KYnQt
            JbjPBDUIREVIFW84qQcKya5qckh4jkoyhKn3N/R9gA8Vw5JTDieThqZRaiIO49c7
            Mw5MFnSJqwBG7uGurZMiMx23pY2+4HwAYakomaKZBSulvM1rRESfpXjgLqyDtOkR
            lukezMTQXDOavfCo486a7UGMHvxP7zdQBdIWJvoD3TlqKyJh6QGCFi4zR///hov8
            s6bc6eRero85Im2BqR2GyuMYyjGTY9Utfpr2W8gU8ZCbRXBKXAi7An3zYds2Mqhp
            6sxBmsVPcBSMHT3nkhm+Wt3A4zfxCdVlGiDi4xnrILM/1k6jlz4LfNIeN4qvRd45
            KZepOfv1JOBay4+nj2xEcWd76zHk45MHbYH/0t3gu0dftqg2ONONhrRVhKYNF2H8
            6r7iImJzGQFzwgfzfi/1Y5ZrzX9zLTWODBcRwaW67K5Zw13BF+iHXZbsOEiUxPrS
            XgGWGbC8oUCdRkgK6rpSq/dGrnFQw2cu+u7muVspMWGcbW3KKJuLxAFehQaU57lg
            MOdoAbzcM3d8Tq8SLfOOAn0iEqJP0BdP0zAWBnvnfG7l4nbj8nz/svYox5xjcYY=
            =bGl0
            -----END PGP MESSAGE-----
          fp: 8ED860B8582DFA86CF887B228E9A833FECDB2CEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
