# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
hostname: bigbang.dev

replicaCount: 1

image:
  repository: rancher/hello-world
  pullPolicy: Always
  tag: v0.1.2

nameOverride: "hello-world"
fullnameOverride: "hello-world"

service:
  port: 80
  
istio:
  enabled: true
  # labels: {}
  # annotations: {}
  gateways:
  - istio-system/main
  hosts:
  - helloworld.{{ .Values.hostname }}
